package view;

import controller.ControladorRequerimientosReto4;
import model.vo.LideresMayorSalario;
import model.vo.LideresProyectosEmblematicos;
import model.vo.MaterialRankeadoImportado;

import java.sql.SQLException;
import java.util.ArrayList;
import java.io.PrintStream;
import java.io.ByteArrayOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.IOException;

public class VistaRequerimientosReto4 extends javax.swing.JFrame{
    public VistaRequerimientosReto4(){
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Nosotros Fuimos");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel1.setText(" Lideres con mayor salario");

        jButton1.setText("Consulta1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Lideres proyectos emblemáticos");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Productos importados");

        jButton2.setText("Consulta2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton3.setText("Consulta3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Información de la base de datos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4))
                .addContainerGap(549, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jButton3)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(385, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(86, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold> 

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:  
     ControladorRequerimientosReto4 controlador = new ControladorRequerimientosReto4();
        System.out.println("*** Lideres con mayor salario ***");     
        ArrayList<LideresMayorSalario> rankingLideresMayorSalario = null;
        try {
            rankingLideresMayorSalario = controlador.consultarLideresMayorSalarios();
        } catch (SQLException ex) {
            Logger.getLogger(ControladorRequerimientosReto4.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Encabezado del resultado
        System.out.println("ID_Lider  Nombre  Primer_Apellido");     
       String printText = null;
       
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
             PrintStream printStream = new PrintStream(outputStream, true))
        {
            for (LideresMayorSalario lideresMayors : rankingLideresMayorSalario) {
                 printStream.print("          "+lideresMayors.getIdLider());
                 printStream.print("   "+lideresMayors.getNombre());
                 printStream.println("       "+lideresMayors.getPrimerApellido());
           printText = outputStream.toString();
        }
        jTextArea1.setText("*** Lideres con mayor salario ***\n"
                 + "ID_Lider  Nombre  Primer_Apellido\n"
                    +printText);
        } catch (IOException ex) {
            Logger.getLogger(ControladorRequerimientosReto4.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (LideresMayorSalario lideresMayors : rankingLideresMayorSalario) {
                 System.out.printf("      %d  %s   %s  %n",
                 lideresMayors.getIdLider(),
                 lideresMayors.getNombre(),
                 lideresMayors.getPrimerApellido()
         );  
        }    
    }  

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        ControladorRequerimientosReto4 controlador = new ControladorRequerimientosReto4();
        System.out.println("*** Lideres proyectos emblemáticos ***");       

        ArrayList<LideresProyectosEmblematicos> rankingProyectosEmblematicos = null;
        try {
            rankingProyectosEmblematicos = controlador.consultarLideresProyectosEmblematicos();
        } catch (SQLException ex) {
            Logger.getLogger(ControladorRequerimientosReto4.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Encabezado del resultado
        System.out.println("Id_Lider  Id_Proyecto  Id_Tipo");
        //Cada VO cargado, mostrarlo en la vista
        
    String printText2 = null;
       
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
             PrintStream printStream = new PrintStream(outputStream, true))
        {
            for (LideresProyectosEmblematicos lideresProyectosE : rankingProyectosEmblematicos) {
                 printStream.print("          "+lideresProyectosE.getIdLider());
                 printStream.print("               "+lideresProyectosE.getIdProyecto());
                 printStream.println("             "+lideresProyectosE.getIdTipo());
           printText2 = outputStream.toString();
        }
        jTextArea2.setText("*** Lideres proyectos emblemáticos ***\n"
                 + "Id_Lider  Id_Proyecto  Id_Tipo\n"
                    +printText2);
        } catch (IOException ex) {
            Logger.getLogger(ControladorRequerimientosReto4.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        for (LideresProyectosEmblematicos lideresProyectosE : rankingProyectosEmblematicos) {
            System.out.printf("      %d         %d       %d %n",
                    lideresProyectosE.getIdLider(),
                    lideresProyectosE.getIdProyecto(),
                    lideresProyectosE.getIdTipo()
            );
        }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        ControladorRequerimientosReto4 controlador = new ControladorRequerimientosReto4();
        System.out.println("*** Productos importados ***");       

        ArrayList<MaterialRankeadoImportado> rankingMaterialesImportados = null;
        try {
            rankingMaterialesImportados = controlador.consultarMaterialesRankeadosImportados();
        } catch (SQLException ex) {
            Logger.getLogger(ControladorRequerimientosReto4.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Cada VO cargado, mostrarlo en la vista
        String printText3 = null;
       
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
             PrintStream printStream = new PrintStream(outputStream, true))
        {
            for (MaterialRankeadoImportado materialImportado : rankingMaterialesImportados) {
                printStream.print("El producto de ID");
                 printStream.print(" "+materialImportado.getIdMaterial());
                 printStream.print(" de descripción:");
                 printStream.print(" "+materialImportado.getNombreMaterial());
                 printStream.print(" de tipo importado(a), tiene un precio de");
                 printStream.println(" "+materialImportado.getPrecioUnidad());
           printText3 = outputStream.toString();
        }
        jTextArea3.setText("*** Productos importados ***\n"
                    +printText3);
        } catch (IOException ex) {
            Logger.getLogger(ControladorRequerimientosReto4.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (MaterialRankeadoImportado materialImportado : rankingMaterialesImportados) {
            System.out.printf("El producto de ID %d de descripción: %s de tipo importado(a), tiene un precio de %d %n",
                    materialImportado.getIdMaterial(),
                    materialImportado.getNombreMaterial(),
                    materialImportado.getPrecioUnidad()
            );
        }
    }             

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRequerimientosReto4().setVisible(true);
            }
        });
        
    
    }


    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;



}
